[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.build]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.start]
cmds = ["python Summarizer.py"]
